from vizdoomgym.envs.vizdoomenv import VizdoomEnv
from vizdoomgym.envs.vizdoombasic import VizdoomBasic
from vizdoomgym.envs.vizdoomcorridor import VizdoomCorridor
from vizdoomgym.envs.vizdoomdefendcenter import VizdoomDefendCenter
from vizdoomgym.envs.vizdoomdefendline import VizdoomDefendLine
from vizdoomgym.envs.vizdoomhealthgathering import VizdoomHealthGathering
from vizdoomgym.envs.vizdoommywayhome import VizdoomMyWayHome
from vizdoomgym.envs.vizdoommywayhomesparse import VizdoomMyWayHomeSparse
from vizdoomgym.envs.vizdoommywayhomeverysparse import VizdoomMyWayHomeVerySparse
from vizdoomgym.envs.vizdoompredictposition import VizdoomPredictPosition
from vizdoomgym.envs.vizdoomtakecover import VizdoomTakeCover
from vizdoomgym.envs.vizdoomdeathmatch import VizdoomDeathmatch
from vizdoomgym.envs.vizdoomhealthgatheringsupreme import VizdoomHealthGatheringSupreme

from vizdoomgym.envs.vizdoomgoalenv import (VizdoomGoalEnv,
	VizDoomMyWayHomeGoal, VizDoomSptmBattleNavigation)
from vizdoomgym.envs.vizdoomenv import (VizdoomTexturedMaze,
	VizdoomTexturedMazeEasy, VizdoomTexturedMazeVerySparse,
	VizdoomTexturedMazeMultiGoal, VizdoomTexturedMazeSuperSparse)
